/**
 * AUTO-DEPLOY PIPELINE
 *
 * Agents can trigger deployments after completing their work.
 * Tracks deployment status, previews, and production releases.
 * Integrates with Railway (primary) and Vercel (fallback).
 */
import { v } from "convex/values";
import { action, mutation, query } from "./_generated/server";
import { api } from "./_generated/api";
import type { Id } from "./_generated/dataModel";

declare const process: { env: Record<string, string | undefined> };

// ─── Deploy Triggers ────────────────────────────────────────────

// Trigger a deployment from a completed mission
export const triggerDeploy = action({
  args: {
    missionId: v.id("missions"),
    projectId: v.id("projects"),
    environment: v.union(v.literal("preview"), v.literal("production")),
    triggeredBy: v.optional(v.string()), // agent run ID or "user"
    commitSha: v.optional(v.string()),
  },
  returns: v.object({
    success: v.boolean(),
    deploymentId: v.optional(v.id("deployments")),
    error: v.optional(v.string()),
  }),
  handler: async (ctx, { missionId, projectId, environment, triggeredBy, commitSha }): Promise<{
    success: boolean;
    deploymentId?: Id<"deployments">;
    error?: string;
  }> => {
    const project = await ctx.runQuery(api.projects.getWithToken, { projectId });
    if (!project) {
      return { success: false, error: "Project not found" };
    }

    // Create deployment record
    const deploymentId = await ctx.runMutation(api.autodeploy.createDeployment, {
      missionId,
      projectId,
      environment,
      triggeredBy: triggeredBy || "system",
      commitSha,
      provider: "railway",
    });

    // Attempt Railway deployment via git push (Railway auto-deploys from main)
    try {
      if (project.githubRepo && project.githubToken) {
        // If we have a branch, merge to main first
        const branches = await ctx.runQuery(api.gitops.getBranches, { missionId });
        const activeBranch = branches.find((b: { status: string }) => b.status === "active" || b.status === "pr_created");

        if (activeBranch && environment === "production") {
          // Create PR if not exists, then merge
          if (!activeBranch.prUrl) {
            const mission = await ctx.runQuery(api.missions.get, { missionId });
            await ctx.runAction(api.gitops.createPR, {
              projectId,
              missionId,
              branchName: activeBranch.branchName,
              title: `[CodeForge] ${mission?.prompt?.slice(0, 80) || "Auto-deploy"}`,
              body: `## Auto-generated by CodeForge Agent Swarm\n\nMission: ${mission?.prompt || "N/A"}\n\nThis PR was automatically created by the CodeForge deployment pipeline.`,
            });
          }
        }

        // Update deployment status
        await ctx.runMutation(api.autodeploy.updateStatus, {
          deploymentId,
          status: "deploying",
          message: "Deployment triggered via Railway auto-deploy from git push",
        });

        return { success: true, deploymentId };
      }

      await ctx.runMutation(api.autodeploy.updateStatus, {
        deploymentId,
        status: "failed",
        message: "No GitHub repo connected — cannot trigger deploy",
      });

      return { success: false, deploymentId, error: "No GitHub repo connected" };
    } catch (e) {
      const msg = e instanceof Error ? e.message : String(e);
      await ctx.runMutation(api.autodeploy.updateStatus, {
        deploymentId,
        status: "failed",
        message: msg,
      });
      return { success: false, deploymentId, error: msg };
    }
  },
});

// ─── Deployment Records ─────────────────────────────────────────

export const createDeployment = mutation({
  args: {
    missionId: v.id("missions"),
    projectId: v.id("projects"),
    environment: v.string(),
    triggeredBy: v.string(),
    commitSha: v.optional(v.string()),
    provider: v.string(),
  },
  returns: v.id("deployments"),
  handler: async (ctx, args) => {
    return await ctx.db.insert("deployments", {
      missionId: args.missionId,
      projectId: args.projectId,
      environment: args.environment,
      triggeredBy: args.triggeredBy,
      commitSha: args.commitSha,
      provider: args.provider,
      status: "pending",
      url: undefined,
      message: "Deployment queued",
      startedAt: Date.now(),
      completedAt: undefined,
    });
  },
});

export const updateStatus = mutation({
  args: {
    deploymentId: v.id("deployments"),
    status: v.string(),
    message: v.optional(v.string()),
    url: v.optional(v.string()),
  },
  returns: v.null(),
  handler: async (ctx, { deploymentId, status, message, url }) => {
    const patch: Record<string, unknown> = { status };
    if (message) patch.message = message;
    if (url) patch.url = url;
    if (status === "success" || status === "failed") {
      patch.completedAt = Date.now();
    }
    await ctx.db.patch(deploymentId, patch);
    return null;
  },
});

// ─── Queries ────────────────────────────────────────────────────

export const listByProject = query({
  args: { projectId: v.id("projects") },
  returns: v.array(v.object({
    _id: v.id("deployments"),
    _creationTime: v.number(),
    missionId: v.id("missions"),
    projectId: v.id("projects"),
    environment: v.string(),
    triggeredBy: v.string(),
    commitSha: v.optional(v.string()),
    provider: v.string(),
    status: v.string(),
    url: v.optional(v.string()),
    message: v.optional(v.string()),
    startedAt: v.number(),
    completedAt: v.optional(v.number()),
  })),
  handler: async (ctx, { projectId }) => {
    return await ctx.db
      .query("deployments")
      .withIndex("by_project", (q) => q.eq("projectId", projectId))
      .order("desc")
      .take(20);
  },
});

export const listByMission = query({
  args: { missionId: v.id("missions") },
  returns: v.array(v.object({
    _id: v.id("deployments"),
    _creationTime: v.number(),
    missionId: v.id("missions"),
    projectId: v.id("projects"),
    environment: v.string(),
    triggeredBy: v.string(),
    commitSha: v.optional(v.string()),
    provider: v.string(),
    status: v.string(),
    url: v.optional(v.string()),
    message: v.optional(v.string()),
    startedAt: v.number(),
    completedAt: v.optional(v.number()),
  })),
  handler: async (ctx, { missionId }) => {
    return await ctx.db
      .query("deployments")
      .withIndex("by_mission", (q) => q.eq("missionId", missionId))
      .order("desc")
      .take(10);
  },
});

export const getLatest = query({
  args: { projectId: v.id("projects") },
  returns: v.union(v.object({
    _id: v.id("deployments"),
    _creationTime: v.number(),
    missionId: v.id("missions"),
    projectId: v.id("projects"),
    environment: v.string(),
    triggeredBy: v.string(),
    commitSha: v.optional(v.string()),
    provider: v.string(),
    status: v.string(),
    url: v.optional(v.string()),
    message: v.optional(v.string()),
    startedAt: v.number(),
    completedAt: v.optional(v.number()),
  }), v.null()),
  handler: async (ctx, { projectId }) => {
    const deployments = await ctx.db
      .query("deployments")
      .withIndex("by_project", (q) => q.eq("projectId", projectId))
      .order("desc")
      .take(1);

    return deployments[0] || null;
  },
});
