/**
 * ═══════════════════════════════════════════════════════════════════
 * CODEFORGE — BRANCH MANAGER
 * ═══════════════════════════════════════════════════════════════════
 *
 * Manages git branches per mission:
 * - Auto-create branches when missions launch
 * - Visual branch tree showing mission → branch mapping
 * - One-click PR creation
 * - Branch status indicators
 */
import { useState } from "react";
import { useAction, useQuery } from "convex/react";
import { api } from "../../../convex/_generated/api";
import type { Id } from "../../../convex/_generated/dataModel";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { ScrollArea } from "@/components/ui/scroll-area";
import { toast } from "sonner";
import {
  GitBranch,
  GitPullRequest,
  GitMerge,
  Loader2,
  Plus,
  ChevronRight,
  Check,
  Clock,
  AlertTriangle,
  Rocket,
  Copy,
} from "lucide-react";

interface BranchManagerProps {
  projectId?: Id<"projects"> | null;
}

interface MissionBranch {
  missionId: string;
  missionName: string;
  branchName: string;
  status: "active" | "completed" | "merged" | "failed";
  filesChanged: number;
  createdAt: number;
}

export function BranchManager({ projectId }: BranchManagerProps) {
  const [creating, setCreating] = useState(false);
  const [newBranchName, setNewBranchName] = useState("");
  const [creatingPR, setCreatingPR] = useState<string | null>(null);

  const missions = useQuery(api.missions.listByProject, projectId ? { projectId } : "skip");
  const project = useQuery(api.projects.get, projectId ? { projectId } : "skip");
  const createBranch = useAction(api.github.createBranch);
  const createPR = useAction(api.github.createPullRequest);

  const gitRepo = project?.githubRepo;

  // Map missions to branches (convention: codeforge/mission-{id-short})
  const missionBranches: MissionBranch[] = (missions || []).map((m: any) => ({
    missionId: m._id,
    missionName: m.prompt?.slice(0, 60) || "Untitled mission",
    branchName: `codeforge/mission-${m._id.toString().slice(-8)}`,
    status: m.status === "running" ? "active" : m.status === "completed" ? "completed" : "failed",
    filesChanged: m.filesModified || 0,
    createdAt: m._creationTime,
  }));

  const handleCreateBranch = async () => {
    if (!gitRepo || !newBranchName) return;
    setCreating(true);
    try {
      const result = await createBranch({
        repo: gitRepo,
        branchName: newBranchName,
      });
      if (result.success) {
        toast.success(`Branch '${newBranchName}' created`);
        setNewBranchName("");
      } else {
        toast.error(result.error || "Failed to create branch");
      }
    } catch (e) {
      toast.error("Failed to create branch");
    }
    setCreating(false);
  };

  const handleCreatePR = async (branch: MissionBranch) => {
    if (!gitRepo) return;
    setCreatingPR(branch.missionId);
    try {
      const result = await createPR({
        repo: gitRepo,
        title: `[CodeForge] ${branch.missionName}`,
        body: `## Mission Output\n\nAutonomously generated by CodeForge AI agents.\n\n**Mission:** ${branch.missionName}\n**Branch:** \`${branch.branchName}\`\n**Files changed:** ${branch.filesChanged}`,
        head: branch.branchName,
      });
      if (result.success) {
        toast.success(`PR #${result.prNumber} created!`);
        if (result.prUrl) window.open(result.prUrl, "_blank");
      } else {
        toast.error(result.error || "Failed to create PR");
      }
    } catch (e) {
      toast.error("Failed to create PR");
    }
    setCreatingPR(null);
  };

  const statusConfig = {
    active: { color: "text-blue-400", bg: "bg-blue-500/10", icon: Clock, label: "Running" },
    completed: { color: "text-emerald-400", bg: "bg-emerald-500/10", icon: Check, label: "Done" },
    merged: { color: "text-purple-400", bg: "bg-purple-500/10", icon: GitMerge, label: "Merged" },
    failed: { color: "text-red-400", bg: "bg-red-500/10", icon: AlertTriangle, label: "Failed" },
  };

  return (
    <div className="h-full flex flex-col bg-[#0a0a0f]">
      {/* Header */}
      <div className="flex items-center justify-between px-3 py-2 border-b border-white/5">
        <div className="flex items-center gap-2">
          <GitBranch className="h-3.5 w-3.5 text-purple-400" />
          <span className="text-xs font-semibold text-white/50">Branch Manager</span>
        </div>
        <Badge className="bg-purple-500/10 text-purple-400 border-purple-500/20 text-[9px]">
          {missionBranches.length} branches
        </Badge>
      </div>

      {/* Create Branch */}
      {gitRepo && (
        <div className="px-3 py-2 border-b border-white/5">
          <div className="flex gap-1.5">
            <Input
              value={newBranchName}
              onChange={(e) => setNewBranchName(e.target.value)}
              placeholder="new-branch-name"
              className="h-7 text-xs bg-white/5 border-white/10"
              onKeyDown={(e) => e.key === "Enter" && handleCreateBranch()}
            />
            <Button
              size="sm"
              className="h-7 text-xs"
              onClick={handleCreateBranch}
              disabled={creating || !newBranchName}
            >
              {creating ? <Loader2 className="h-3 w-3 animate-spin" /> : <Plus className="h-3 w-3" />}
            </Button>
          </div>
          <p className="text-[9px] text-white/15 mt-1">
            Repo: {gitRepo}
          </p>
        </div>
      )}

      {!gitRepo && (
        <div className="p-4 text-center">
          <GitBranch className="h-8 w-8 text-white/10 mx-auto mb-2" />
          <p className="text-xs text-white/20">Connect a GitHub repo to use branch management</p>
        </div>
      )}

      {/* Branch List */}
      <ScrollArea className="flex-1">
        <div className="p-2 space-y-1">
          {/* Main branch */}
          <div className="rounded-lg bg-white/[0.02] border border-white/[0.04] p-2.5">
            <div className="flex items-center gap-2">
              <GitBranch className="h-3 w-3 text-emerald-400" />
              <span className="text-[11px] font-semibold text-white/50">main</span>
              <Badge className="ml-auto bg-emerald-500/10 text-emerald-400 border-emerald-500/20 text-[8px]">
                default
              </Badge>
            </div>
          </div>

          {/* Mission branches */}
          {missionBranches.map((branch) => {
            const config = statusConfig[branch.status];
            const StatusIcon = config.icon;
            return (
              <div
                key={branch.missionId}
                className="rounded-lg bg-white/[0.02] border border-white/[0.04] p-2.5 space-y-1.5"
              >
                <div className="flex items-center gap-2">
                  <GitBranch className={`h-3 w-3 ${config.color}`} />
                  <span className="text-[10px] font-mono text-white/40 truncate flex-1">
                    {branch.branchName}
                  </span>
                  <button
                    onClick={() => {
                      navigator.clipboard.writeText(branch.branchName);
                      toast.success("Copied!");
                    }}
                    className="text-white/10 hover:text-white/30"
                  >
                    <Copy className="h-2.5 w-2.5" />
                  </button>
                </div>

                {/* Mission info */}
                <div className="flex items-start gap-1.5">
                  <Rocket className="h-2.5 w-2.5 text-white/10 mt-0.5 shrink-0" />
                  <span className="text-[9px] text-white/20 line-clamp-2">{branch.missionName}</span>
                </div>

                {/* Status + Actions */}
                <div className="flex items-center gap-2">
                  <Badge className={`${config.bg} ${config.color} border-0 text-[8px] gap-0.5`}>
                    <StatusIcon className="h-2 w-2" />
                    {config.label}
                  </Badge>

                  {branch.status === "completed" && gitRepo && (
                    <Button
                      size="sm"
                      variant="ghost"
                      className="h-5 text-[9px] text-purple-400 hover:text-purple-300 ml-auto gap-0.5 px-1.5"
                      onClick={() => handleCreatePR(branch)}
                      disabled={creatingPR === branch.missionId}
                    >
                      {creatingPR === branch.missionId ? (
                        <Loader2 className="h-2.5 w-2.5 animate-spin" />
                      ) : (
                        <>
                          <GitPullRequest className="h-2.5 w-2.5" />
                          Create PR
                        </>
                      )}
                    </Button>
                  )}
                </div>
              </div>
            );
          })}

          {missionBranches.length === 0 && gitRepo && (
            <div className="text-center py-6">
              <p className="text-[10px] text-white/15">
                Branches will appear here as missions run
              </p>
            </div>
          )}
        </div>
      </ScrollArea>
    </div>
  );
}
